/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.controller;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import model.detail_transaksi;
import model.pegawai;
import model.transaksi;
import model.barang;


public class transaksiview extends javax.swing.JFrame {
        controller controller;
        ArrayList<detail_transaksi> arrKeranjang;
        Double Harga_Total;
        Integer role;
    /**
     * Creates new form Transaksi
     * @throws java.sql.SQLException
     */
    public transaksiview(int role) throws SQLException {
        initComponents();
        this.controller = new controller();
        this.arrKeranjang = new ArrayList<>();
        this.Harga_Total = 0.0;
        this.showComboBoxPegawai();
        this.showComboBoxProduk();
        this.showTabelKeranjang();
        this.showTabelTransaksi();
        this.role = role;
        if(this.role == 1){
            jMenu3.show(false);
        }
    }
    
    private void showComboBoxPegawai() throws SQLException {
        DefaultComboBoxModel dtmPegawai = new DefaultComboBoxModel();
        for(pegawai p : this.controller.getDataPegawai()){
            dtmPegawai.addElement(p.getNama());
        }
        
        this.cbPegawai.setModel(dtmPegawai);
    }
            
        private void showComboBoxProduk() throws SQLException {
        DefaultComboBoxModel dtmProduk = new DefaultComboBoxModel();
        for(barang p : this.controller.getDataBarang()){
            dtmProduk.addElement(p.getNama_barang()+ " ( " + p.getStok()+ " )");
        }
        this.cbProduk.removeAll();
        this.cbProduk.setModel(dtmProduk);
    }
        
        private void showTabelKeranjang(){
            DefaultTableModel dtmKeranjang = new DefaultTableModel(new String[]{"NAMA PRODUK", "HARGA SATUAN", "JUMLAH"},0);
            dtmKeranjang.setRowCount(0);
            
            for(detail_transaksi dp : this.arrKeranjang){
                dtmKeranjang.addRow(new String[]{dp.getBarang().getNama_barang().toString(), dp.getBarang().getHarga_satuan().toString(), dp.getJumlah().toString()});
            }
            
            this.tblKeranjang.setModel(dtmKeranjang);
        }
        
        private void setHargaTotal(){
            this.tfTotalHarga.setText(String.valueOf(this.Harga_Total));
        }
        
        private void showTabelTransaksi() throws SQLException{
            DefaultTableModel dtmPemesanan = new DefaultTableModel(new String[]{"PEGAWAI", "TANGGAL TANSAKSI", "HARGA_TOTAL"},0);
            dtmPemesanan.setRowCount(0);
            
            for(transaksi p : this.controller.getDataTransaksi()){
                dtmPemesanan.addRow(new String[]{p.getPegawai().getNama(), p.getTanggal_transaksi().toString(), p.getHarga_total().toString()});
            }
            this.tblPesanan.setModel(dtmPemesanan);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbPegawai = new javax.swing.JComboBox<String>();
        tfTglPengiriman = new javax.swing.JTextField();
        cbProduk = new javax.swing.JComboBox<String>();
        tfJumlah = new javax.swing.JTextField();
        tfTotalHarga = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKeranjang = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPesanan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetail_Pemesanan = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnLihatDetail = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Pegawai");

        jLabel5.setText("Tgl Transaksi");

        jLabel6.setText("Barang");

        jLabel7.setText("Jumlah");

        jLabel9.setText("Total Harga");

        cbPegawai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbProduk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblKeranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKeranjang);

        tblPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblPesanan);

        taDetail_Pemesanan.setColumns(20);
        taDetail_Pemesanan.setRows(5);
        jScrollPane3.setViewportView(taDetail_Pemesanan);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnLihatDetail.setText("Lihat Detail");
        btnLihatDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatDetailActionPerformed(evt);
            }
        });

        jMenu3.setText("PEGAWAI");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("BARANG");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("TRANSAKSI");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTglPengiriman)
                            .addComponent(cbProduk, 0, 204, Short.MAX_VALUE)
                            .addComponent(tfJumlah)
                            .addComponent(cbPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfTotalHarga)))
                    .addComponent(btnTambah))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLihatDetail)
                        .addGap(161, 161, 161))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTglPengiriman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnTambah)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(btnSimpan))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLihatDetail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
            try {
                detail_transaksi dp = new detail_transaksi();
                dp.setJumlah(Integer.parseInt(this.tfJumlah.getText()));
                dp.setBarang(this.controller.getDataBarang().get(this.cbProduk.getSelectedIndex()));
                Harga_Total += this.controller.getDataBarang().get(cbProduk.getSelectedIndex()).getHarga_satuan()* Integer.parseInt(tfJumlah.getText());
                this.setHargaTotal();
                this.arrKeranjang.add(dp);
                this.showTabelKeranjang();
                this.tfJumlah.setText("");
                
            } catch (SQLException ex) {
                Logger.getLogger(transaksiview.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        transaksi transaksi = new transaksi();
            try {
                transaksi.setPegawai(this.controller.getDataPegawai().get(this.cbPegawai.getSelectedIndex()));
                transaksi.setTanggal_transaksi(new Date());
                transaksi.setHarga_total(this.Harga_Total);
                transaksi.setArrDetail_Transaksi(this.arrKeranjang);
                this.controller.insertTransaksi(transaksi);
                this.showTabelTransaksi();
                this.arrKeranjang = new ArrayList<>();
                this.showTabelKeranjang();
                this.Harga_Total = 0.0;
                this.setHargaTotal();
                this.showComboBoxProduk();
            } catch (SQLException err) {
                System.out.println(err);
            }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnLihatDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatDetailActionPerformed
            try {
                transaksi transaksi = this.controller.getDataTransaksi().get(tblPesanan.getSelectedRow());
                String text = ""
                        + "========================= PEGAWAI =============================="+ "\n"
                        + "NAMA : " + transaksi.getPegawai().getNama() + "\n"
                        + "ALAMAT : " + transaksi.getPegawai().getAlamat() + "\n"
                        + "NO TELP : " + transaksi.getPegawai().getNo_telp()+ "\n"
                        + "======================= PEMESANAN =============================="+ "\n"
                        + "TANGGAL TRANSAKSI : " + new SimpleDateFormat("dd/MM/yyyy").format(transaksi.getTanggal_transaksi()) + "\n"
                        + "HARGA TOTAL = " + transaksi.getHarga_total()+ "\n\n"
                        + "======================== PRODUK =============================="+ "\n" ;
                ArrayList<detail_transaksi> dp = transaksi.getArrDetail_Transaksi();
                for(int i=0;i < dp.size();i++){
                    text += "\n" + (i+1) + ". \n"
                            + "NAMA BARANG          : " + dp.get(i).getBarang().getNama_barang()+ "\n"
                            + "HARGA SATUAN         : " + dp.get(i).getBarang().getHarga_satuan()+ "\n"
                            + "STOK BARANG         : " + dp.get(i).getBarang().getStok()+ "\n"
                            + "JUMLAH BELI PRODUK   : " + dp.get(i).getJumlah() + "\n";
                }
                this.taDetail_Pemesanan.setText(text);
            } catch (SQLException ex) {
                Logger.getLogger(transaksiview.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_btnLihatDetailActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
            try {
                // TODO add your handling code here:
                new form_barang(role).show();
            } catch (SQLException ex) {
                Logger.getLogger(transaksiview.class.getName()).log(Level.SEVERE, null, ex);
            }
        this.dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        try {
            new form_pegawai(role).show();
        } catch (SQLException ex) {
            Logger.getLogger(form_barang.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_jMenu3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLihatDetail;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbPegawai;
    private javax.swing.JComboBox<String> cbProduk;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea taDetail_Pemesanan;
    private javax.swing.JTable tblKeranjang;
    private javax.swing.JTable tblPesanan;
    private javax.swing.JTextField tfJumlah;
    private javax.swing.JTextField tfTglPengiriman;
    private javax.swing.JTextField tfTotalHarga;
    // End of variables declaration//GEN-END:variables



    


}
